### ISSUE TITLE
The text file after hadoop operation

### ISSUE THREAD

**Issue by CodingPerson** [Anna146/CHARM#2]
I am very interested in your topic, but due to hardware problems, there is no Hadoop environment, could you please send me the text file obtained after Hadoop operation?Thank you very much

**Comment by Anna146** [comment]
ok pls give me your email address

**Comment by CodingPerson** [comment]
Thank you very much. This is my email 1440624049@qq.com




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anna146/CHARM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月20日(星期四) 晚上11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Anna146/CHARM] The text file after hadoop operation (#2)





 
ok pls give me your email address

**Comment by CodingPerson** [comment]
Thank you very much for your reply. However, I noticed that you only sent me a small part of the data. Could you please send me the complete data?I am grateful for that

**Comment by CodingPerson** [comment]
I'm sorry to tell you that the data you provided to me is still incomplete. According to the file ids.txt, there should be 538,967 pieces of data. I can't get the results in the paper according to the data you provided, so I hope you can provide me with the complete text data, thank you very much

**Comment by Anna146** [comment]
sure but number of texts taken from hadoop should not necessarily match the number of ids

**Comment by CodingPerson** [comment]
Thank you very much for your reply, but I can't get the result in the paper now. I wonder if it is caused by the incomplete data you provided?

**Comment by Anna146** [comment]
could you please provide me with details on the training folds you get like the number of users per fold for each predicate?
