### ISSUE TITLE
miss the file

### ISSUE THREAD

**Issue by CodingPerson** [Anna146/CHARM#3]
![image](https://user-images.githubusercontent.com/45897585/119437199-376f3380-bd50-11eb-805e-1fce5b356203.png)
As shown in the figure above, in results_unseen.py, I found that I needed profession_count.txt and hobby_count.txt, but I didn't find those two files. 
Meanwhile, I noticed that you provided some data in the link http://bit.ly/charm20 in your paper, in which there is a file profession_count.txt in the profession folder, but there is no file hobby_count.txt in the hobby folder.
Could you please provide it to me?Thank you very much

**Comment by Anna146** [comment]
Just comment it out, it is not used anywhere
